
export const RESERVATION_ACTION_TYPE = {
    ADD_NEW_RESERVATION: 'ADD_NEW_RESERVATION',
    CANCEL_RESERVATION: 'CANCEL_RESERVATION',
    CONFIRM_RESERVATION: 'CONFIRM_RESERVATION',
    ADD_NEW_DAY: 'ADD_NEW_DAY',
    FETCH_FROM_DB: 'FETCH_FROM_DB'
}