
export const RESERVATION_ACTION_TYPE = {
    ADD_NEW_RESERVATION: 'ADD_NEW_RESERVATION',
    DELETE_RESERVATION: 'DELETE_RESERVATION',
    CONFIRM_RESERVATION: 'CONFIRM_RESERVATION',
    ADD_NEW_DAY: 'ADD_NEW_DAY'
}